### ISSUE TITLE
I don't understand how to use this

### ISSUE THREAD

**Issue by evancaldwell** [milesje/papa-parser#2]
I don't understand what event to listen for when the file is parsed or how to get the data from the parsed file. The demo doesn't show any of that and there are no methods or events shown in the documentation.

I set up a clean polymer project, bower installed papa-parser, put it on an element and the button shows up, clicking on it shows the file select dialog but I'm stuck from there. I tried to data-bind outputData on the element declaration but that didn't seem to do anything. Any help would be appreciated.

**Comment by milesje** [comment]
if you are correctly binding to the outputData than you should be receiving the data. I will run some test later tonight to double check. If not I will add the data to a custom event.

**Comment by milesje** [comment]
OK, after doing some investigation it turns out that the web component I am using for the file input is no longer working. I will be reworking this element so that it doesn't handle the file input itself instead it will require you to hand it the file and it will hand back the JSON. It will take a little while to rework this as I am already swamped with other work.

**Comment by evancaldwell** [comment]
No problem, thanks for taking a look. I'll wait to hear from you.

**Comment by milesje** [comment]
OK, I have made some changes to the code base and I have it working for my simple test data. You can take a look at this now and see if you can figure out how to use it. The component itself doesn't have any visual elements to it so its much like iron-ajax in that sense. You will need to profide the CSV data in a String format, and then listen for the papa-parser-complete event which will contain the JSON data. If you still need help please let me know.
